"""
app.py — Streamlit UI for the AI Content Engine.

WHY Streamlit (not Flask/FastAPI + React):
  For a one-day lab, Streamlit gives a production-looking UI in ~100 lines of
  Python with no JavaScript. The tradeoff is less UI flexibility and single-
  threaded execution, but neither matters at this scale.

WHY a two-column layout (text left, visuals right):
  Campaign review workflows are text-first: marketers read copy before
  approving visuals. Placing text on the left mirrors natural reading order
  and lets the hero image and video take the full right column without
  competing with long text blocks.
"""

import streamlit as st
from text_gen import generate_tagline, generate_blog_intro, generate_social_posts, MAX_PRODUCT_LEN, MAX_AUDIENCE_LEN, MAX_TONE_LEN
from image_gen import generate_hero_image, COST_PER_IMAGE_USD
from video_gen import generate_promo_video, DURATION_SECONDS, COST_PER_SECOND_USD

# ---------------------------------------------------------------------------
# Page config — must be the first Streamlit call
# ---------------------------------------------------------------------------
st.set_page_config(page_title="AI Content Engine", layout="wide")
st.title("🎯 AI Content Engine")

# ---------------------------------------------------------------------------
# AI Disclosure — shown once at the top on every load.
#
# WHY show this unconditionally (not hidden behind a toggle):
#   GDPR and emerging AI transparency regulations require users to know when
#   content is AI-generated before they interact with the system. A persistent
#   notice is more reliable than a one-time modal that can be dismissed and
#   forgotten.
# ---------------------------------------------------------------------------
st.info(
    "⚠️ **AI Disclosure:** All content generated by this app — taglines, blog copy, "
    "social posts, images, and video — is produced by AI models (DeepSeek R1, FLUX.2, "
    "Wan 2.6). It has not been reviewed by a human. Always fact-check, brand-check, "
    "and legal-review AI-generated marketing content before publishing.",
    icon="🤖",
)

# ---------------------------------------------------------------------------
# Sidebar — Input form + stats + cost awareness
# ---------------------------------------------------------------------------
with st.sidebar:
    st.header("📋 Product Brief")

    # WHY show character limits in placeholders:
    #   Users need to know the constraint before they hit it, not after a
    #   validation error. Inline hints reduce friction and support errors.
    product = st.text_input(
        "Product name",
        placeholder=f"e.g. Sparkling Mango Juice (max {MAX_PRODUCT_LEN} chars)",
        max_chars=MAX_PRODUCT_LEN,
    )
    audience = st.text_input(
        "Target audience",
        placeholder=f"e.g. health-conscious millennials (max {MAX_AUDIENCE_LEN} chars)",
        max_chars=MAX_AUDIENCE_LEN,
    )
    tone = st.text_input(
        "Brand tone",
        placeholder=f"playful / premium / eco / bold / minimal / retro (max {MAX_TONE_LEN} chars)",
        max_chars=MAX_TONE_LEN,
    )
    clicked = st.button("🚀 Generate Campaign", use_container_width=True)

    # ---------------------------------------------------------------------------
    # Technique reference card
    # WHY display technique labels in the sidebar (not only on output cards):
    #   Having the techniques visible before generation shows design intent.
    #   Users can see what approach drives each asset before the run completes.
    # ---------------------------------------------------------------------------
    st.divider()
    st.markdown("### 🧠 Techniques Used")
    st.markdown(
        "| Asset | Technique |\n"
        "|---|---|\n"
        "| Tagline | Few-shot prompting |\n"
        "| Blog intro | Role-based prompting |\n"
        "| Social posts | Structured output (JSON) |\n"
        "| Hero image | Image prompt formula |\n"
        "| Video | Image-to-video + motion prompt |"
    )

    # ---------------------------------------------------------------------------
    # Cost awareness panel
    # WHY show estimated cost before the user clicks:
    #   Showing the estimate upfront lets users make an informed decision,
    #   especially if they have a limited API credit balance. The video at
    #   $0.50 dominates total cost.
    # ---------------------------------------------------------------------------
    st.divider()
    st.markdown("### 💰 Estimated Cost Per Run")
    text_cost = 0.003  # 3 LLM calls × ~$0.001 average
    image_cost = COST_PER_IMAGE_USD
    video_cost = DURATION_SECONDS * COST_PER_SECOND_USD
    total_cost = text_cost + image_cost + video_cost
    st.markdown(
        f"- Text (3 calls): ~${text_cost:.3f}\n"
        f"- Image (FLUX.2): ~${image_cost:.3f}\n"
        f"- Video (Wan 2.6, {DURATION_SECONDS}s): ~${video_cost:.2f}\n"
        f"- **Total: ~${total_cost:.2f}**\n\n"
        f"At 100 runs/day: ~${total_cost * 100 * 30:.0f}/month"
    )

    # ---------------------------------------------------------------------------
    # Content safety notice
    # WHY in sidebar (not buried in disclosure):
    #   Users who scroll past the top disclosure will still see this. Placing
    #   it near the Generate button ties it to the action of generating content.
    # ---------------------------------------------------------------------------
    st.divider()
    st.markdown("### 🛡️ Content Safety")
    st.caption(
        "This tool generates marketing content only. "
        "Do not use it to generate medical, legal, financial, or political content. "
        "AI-generated content may reflect biases present in training data — "
        "review all output before publishing."
    )

# ---------------------------------------------------------------------------
# Main area — two-column output layout
# ---------------------------------------------------------------------------
left, right = st.columns([1.2, 1])

if clicked:
    # ------------------------------------------------------------------
    # Input validation — beyond the max_chars already enforced by the widget.
    # WHY validate again here: max_chars only truncates silently in Streamlit;
    # we want an explicit error if inputs are empty or whitespace-only.
    # ------------------------------------------------------------------
    product  = product.strip()
    audience = audience.strip()
    tone     = tone.strip()

    errors = []
    if not product:
        errors.append("Product name is required.")
    if not audience:
        errors.append("Target audience is required.")
    if not tone:
        errors.append("Brand tone is required.")

    if errors:
        for err in errors:
            st.warning(err)
        st.stop()

    # ------------------------------------------------------------------
    # CALL 1 — Tagline (feeds into calls 2 and 4)
    # ------------------------------------------------------------------
    with st.spinner("Generating tagline..."):
        try:
            tagline = generate_tagline(product, audience, tone)
        except Exception as e:
            left.error(f"❌ Tagline failed: {e}")
            st.stop()

    # ------------------------------------------------------------------
    # CALL 2 — Blog introduction (role-based, uses tagline)
    # ------------------------------------------------------------------
    with st.spinner("Writing blog introduction..."):
        try:
            blog_text = generate_blog_intro(product, audience, tone, tagline)
        except Exception as e:
            blog_text = None
            left.error(f"❌ Blog intro failed: {e}")

    # ------------------------------------------------------------------
    # CALL 3 — Social posts (structured JSON, uses product + tone only)
    # ------------------------------------------------------------------
    with st.spinner("Creating social posts..."):
        try:
            social_json = generate_social_posts(product, tone)
        except Exception as e:
            social_json = None
            left.error(f"❌ Social posts failed: {e}")

    # ------------------------------------------------------------------
    # CALL 4 — Hero image (uses product + tagline + tone)
    # ------------------------------------------------------------------
    with st.spinner("Generating hero image (FLUX.2)..."):
        try:
            hero_image_bytes = generate_hero_image(product, tagline, tone)
        except Exception as e:
            hero_image_bytes = None
            right.error(f"❌ Hero image failed: {e}")

    # ------------------------------------------------------------------
    # CALL 5 — Promotional video (depends on call 4; skip if image failed)
    # WHY guard with `if hero_image_bytes`: downstream call would crash
    # without a valid image. Failing gracefully here is better than an
    # unhandled exception that wipes the entire output.
    # ------------------------------------------------------------------
    video_bytes = None
    if hero_image_bytes:
        with st.spinner("Rendering promo video — this takes ~90 seconds..."):
            try:
                video_bytes = generate_promo_video(hero_image_bytes)
            except Exception as e:
                right.error(f"❌ Video generation failed: {e}")

    # ------------------------------------------------------------------
    # Render text assets (left column)
    # ------------------------------------------------------------------
    with left:
        if tagline:
            st.markdown("### 🏷️ Campaign Tagline")
            st.info(f"**{tagline}**")
            st.caption("Technique: Few-shot prompting — tone-calibrated examples injected into the prompt")

        if blog_text:
            st.markdown("### 📝 Blog Introduction")
            st.markdown(
                f'<div style="background:#f9f9f9;padding:1rem;border-radius:8px;'
                f'line-height:1.7">{blog_text}</div>',
                unsafe_allow_html=True,
            )
            st.caption("Technique: Role-based prompting — content strategist persona")

        if social_json:
            st.markdown("### 📱 Social Media Posts")
            st.caption("Technique: Structured output (JSON) — platform-specific character limits enforced in code")

            st.markdown("**Twitter / X**")
            twitter_text = social_json.get("twitter", "")
            st.text_area("", twitter_text, height=80, key="tw", disabled=True)
            st.caption(f"{len(twitter_text)} / 280 chars")

            st.markdown("**Instagram**")
            instagram_text = social_json.get("instagram", "")
            st.text_area("", instagram_text, height=120, key="ig", disabled=True)
            st.caption(f"{len(instagram_text)} / 2200 chars")

            st.markdown("**LinkedIn**")
            linkedin_text = social_json.get("linkedin", "")
            st.text_area("", linkedin_text, height=100, key="li", disabled=True)
            st.caption(f"{len(linkedin_text)} / 700 chars")

    # ------------------------------------------------------------------
    # Render visual assets (right column)
    # ------------------------------------------------------------------
    with right:
        if hero_image_bytes:
            st.markdown("### 🎨 Hero Image")
            st.image(hero_image_bytes, use_container_width=True)
            st.caption("Technique: Image prompt formula — subject + style (from tone) + composition + constraints (FLUX.2 Klein)")

        if video_bytes:
            st.markdown("### 🎬 Promotional Video")
            st.video(video_bytes)
            st.caption("Technique: Image-to-video with motion prompt — slow cinematic push-in (Wan 2.6, 5s at 720p)")

    # ------------------------------------------------------------------
    # Post-generation AI content reminder
    # WHY show again after generation (not only before):
    #   The disclosure at the top may have scrolled out of view by the time
    #   the user is looking at the generated assets. A brief reminder here
    #   ensures it's seen in context.
    # ------------------------------------------------------------------
    st.divider()
    st.caption(
        "🤖 All assets above are AI-generated. Review for accuracy, brand alignment, "
        "and legal compliance before use."
    )

else:
    left.markdown(
        "**How to use:**\n\n"
        "1. Fill in the three fields in the sidebar\n"
        "2. Click **Generate Campaign**\n"
        "3. All five assets generate in one run (~2 minutes including video)\n\n"
        "*Each asset uses a different AI technique — labels appear below each result.*"
    )
